version: '3'
services:
  kafka:
    build: ./kafka
    ports:
      - 9092:9092 # Kafka port
  nifi:
    image: apache/nifi:latest
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=ctsBtRBKHRAx69EqUghvvgEvjnaLjFEB
    ports:
      - 8443:8443
